project:
  type: website
  output-dir: docs

website:
  title: "aksandhu23.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
    - mystyles.scss
    mainfont: Raleway
    css: styles.css
    toc: true

editor: visual

